### ISSUE TITLE
[Bug] Custom pots interfere with passive particle generation

### ISSUE THREAD

**Issue by Arkraze** [SuperMartijn642/Pottery#7]
**Version Info**
- Minecraft, 1.20.4
- Pottery, 1.0.1
- supermartijn642configlib 1.1.8+a
- supermartijn642corelib 1.1.17+a

**What mod loader are you using?**: Fabric 0.15.11

**Description of the Bug**
Placing a custom pot causes campfires (normal, soul, & signal fire) to incorrectly generate smoke, either making none or a constant stream of particles, depending on placement timing. Removing all custom pots or moving beyond the block entity render distance of the pots fixes the smoke, but rebreaks when a pot is placed or comes back in sight. Persists if the pots are occluded or behind the camera, and through relaunch.

**Steps to Reproduce**
Place any Pottery pot, of any color, and a campfire, in any order.

**Screenshots**
![2024-06-26_00 27 14](https://github.com/SuperMartijn642/Pottery/assets/50601818/f3847798-4293-4f3e-ad2a-f4e9baef991c)
![2024-06-26_00 27 20](https://github.com/SuperMartijn642/Pottery/assets/50601818/b4018345-01ed-4fa9-8364-557eb64cacf1)

**Comment by Arkraze** [comment]
Did some further testing, the issue is on 1.20.1 fabric as well. There are no logged errors. The default pot and block entities from your Benched mod don't present these issues, if that helps.

Persists through settings changes (some of dubious relevance):
- Graphics: fast, fancy, fabulous
- Particles: minimal, decreased, all
- Smooth lighting I/O
- Vsync I/O
- Fullscreen/windowed

Persists through pot interactions:
- Block wobbling
- Adding items
- Exchanging sherds

Interferes with passively generated particles (non-comprehensive):
- Bubble columns
- Campfire sparks (in addition to smoke), lava & fire sparks
- Dripping particles from water/lava above a block, as well as dripstone
- Torches, redstone components

No interference on ephemeral particles (non-comprehensive):
- Broken block particles
- Lava-water interaction
- Splash & lingering potions
- Eating particles
- Rain
- On-damage/enchantment particles (e.g. sharpness)

![2024-07-06_19 57 43](https://github.com/SuperMartijn642/Pottery/assets/50601818/88ed505d-52ba-4403-a6e1-83d9e8cf095c)

**Comment by SuperMartijn642** [comment]
Seems the rendering was resetting the random state, hence anything determined from the random after would be the same every time.
I fixed it now in Pottery version 1.0.2.
Thank you for reporting the issue!
